"""
Art. 13 GDPR-compliant privacy policy in 4 languages.
Controller: AMIGA, z.s.  |  IČO 22852221  |  Záhřebská 539/15, Praha 2
"""

PRIVACY_POLICY: dict[str, str] = {
    "UA": (
        "<b>🔒 Політика конфіденційності — Reachable</b>\n\n"
        "<b>1. Контролер даних</b>\n"
        "AMIGA, z.s. (IČO 22852221)\n"
        "Záhřebská 539/15, Praha 2, 120 00, Чехія\n"
        "info@amiga-migrant.cz | +420 736 101 609\n\n"
        "<b>2. Які дані ми збираємо та навіщо</b>\n"
        "Ім'я, контактні дані (телефон, e-mail), вік, мова та опис ситуації — для підбору спеціаліста психологічної підтримки. "
        "Правова підстава: явна згода (ст. 6(1)(a) GDPR).\n\n"
        "<b>3. Дані особливих категорій (ст. 9 GDPR)</b>\n"
        "Опис ситуації може містити інформацію про психічне здоров'я. Ми обробляємо її виключно для надання підтримки. "
        "Правова підстава: явна згода (ст. 9(2)(a) GDPR). Згоду можна відкликати будь-коли.\n\n"
        "<b>4. Зберігання даних</b>\n"
        "Дані зберігаються під час реєстрації. Видаляються негайно за командою /deleteme або протягом 30 днів з останньої активності.\n\n"
        "<b>5. Ваші права</b>\n"
        "Доступ, виправлення, <b>видалення</b> (/deleteme), обмеження, перенесення та відкликання згоди.\n"
        "Звернення: gdpr@amiga-migrant.cz\n\n"
        "<b>6. Треті сторони (обробники)</b>\n"
        "• Google LLC — Calendar і Sheets (угода про обробку через Google Workspace)\n"
        "• Telegram Messenger — лише транспорт\n"
        "• Render Inc. — хостинг\n"
        "Дані не продаються та не передаються у комерційних цілях.\n\n"
        "<b>7. Контакт із питань GDPR</b>\n"
        "gdpr@amiga-migrant.cz\n\n"
        "<b>8. Наглядовий орган</b>\n"
        "Úřad pro ochranu osobních údajů (ÚOOÚ)\n"
        "www.uoou.cz"
    ),
    "RU": (
        "<b>🔒 Политика конфиденциальности — Reachable</b>\n\n"
        "<b>1. Контролёр данных</b>\n"
        "AMIGA, z.s. (IČO 22852221)\n"
        "Záhřebská 539/15, Praha 2, 120 00, Чехия\n"
        "info@amiga-migrant.cz | +420 736 101 609\n\n"
        "<b>2. Какие данные мы собираем и зачем</b>\n"
        "Имя, контактные данные (телефон, e-mail), возраст, язык и описание ситуации — для подбора специалиста психологической поддержки. "
        "Правовое основание: явное согласие (ст. 6(1)(a) GDPR).\n\n"
        "<b>3. Данные особых категорий (ст. 9 GDPR)</b>\n"
        "Описание ситуации может содержать сведения о психическом здоровье. Мы обрабатываем их исключительно для оказания поддержки. "
        "Правовое основание: явное согласие (ст. 9(2)(a) GDPR). Согласие можно отозвать в любой момент.\n\n"
        "<b>4. Хранение данных</b>\n"
        "Данные хранятся во время регистрации. Удаляются немедленно по команде /deleteme или в течение 30 дней с последней активности.\n\n"
        "<b>5. Ваши права</b>\n"
        "Доступ, исправление, <b>удаление</b> (/deleteme), ограничение, перенос и отзыв согласия.\n"
        "Обращения: gdpr@amiga-migrant.cz\n\n"
        "<b>6. Третьи стороны (обработчики)</b>\n"
        "• Google LLC — Calendar и Sheets (соглашение через Google Workspace)\n"
        "• Telegram Messenger — только транспорт\n"
        "• Render Inc. — хостинг\n"
        "Данные не продаются и не передаются в коммерческих целях.\n\n"
        "<b>7. Контакт по вопросам GDPR</b>\n"
        "gdpr@amiga-migrant.cz\n\n"
        "<b>8. Надзорный орган</b>\n"
        "Úřad pro ochranu osobních údajů (ÚOOÚ)\n"
        "www.uoou.cz"
    ),
    "CZ": (
        "<b>🔒 Zásady ochrany osobních údajů — Reachable</b>\n\n"
        "<b>1. Správce osobních údajů</b>\n"
        "AMIGA, z.s. (IČO 22852221)\n"
        "Záhřebská 539/15, Praha 2, 120 00, Česká republika\n"
        "info@amiga-migrant.cz | +420 736 101 609\n\n"
        "<b>2. Jaké údaje sbíráme a proč</b>\n"
        "Jméno, kontaktní údaje (telefon, e-mail), věk, jazyk a popis situace — za účelem přiřazení specialisty psychologické podpory. "
        "Právní základ: výslovný souhlas (čl. 6(1)(a) GDPR).\n\n"
        "<b>3. Zvláštní kategorie osobních údajů (čl. 9 GDPR)</b>\n"
        "Popis situace může obsahovat informace o duševním zdraví. Zpracováváme je výhradně za účelem poskytnutí podpory. "
        "Právní základ: výslovný souhlas (čl. 9(2)(a) GDPR). Souhlas lze kdykoli odvolat.\n\n"
        "<b>4. Uchovávání údajů</b>\n"
        "Údaje jsou uchovávány po dobu registrace. Jsou smazány okamžitě na žádost /deleteme nebo do 30 dnů od poslední aktivity.\n\n"
        "<b>5. Vaše práva</b>\n"
        "Přístup, oprava, <b>výmaz</b> (/deleteme), omezení zpracování, přenositelnost a odvolání souhlasu.\n"
        "Žádosti: gdpr@amiga-migrant.cz\n\n"
        "<b>6. Třetí strany (zpracovatelé)</b>\n"
        "• Google LLC — Calendar a Sheets (smlouva přes Google Workspace)\n"
        "• Telegram Messenger — pouze přenos zpráv\n"
        "• Render Inc. — hosting\n"
        "Data nejsou prodávána ani sdílena pro komerční účely.\n\n"
        "<b>7. Kontakt pro GDPR</b>\n"
        "gdpr@amiga-migrant.cz\n\n"
        "<b>8. Dozorový úřad</b>\n"
        "Úřad pro ochranu osobních údajů (ÚOOÚ)\n"
        "www.uoou.cz"
    ),
    "EN": (
        "<b>🔒 Privacy Policy — Reachable</b>\n\n"
        "<b>1. Data Controller</b>\n"
        "AMIGA, z.s. (IČO 22852221)\n"
        "Záhřebská 539/15, Praha 2, 120 00, Czech Republic\n"
        "info@amiga-migrant.cz | +420 736 101 609\n\n"
        "<b>2. Data we collect and why</b>\n"
        "Name, contact details (phone, e-mail), age, language and situation description — to match you with a psychological support specialist. "
        "Legal basis: explicit consent (Art. 6(1)(a) GDPR).\n\n"
        "<b>3. Special-category data (Art. 9 GDPR)</b>\n"
        "Your situation description may contain mental health information. We process it solely to provide support. "
        "Legal basis: explicit consent (Art. 9(2)(a) GDPR). You may withdraw consent at any time.\n\n"
        "<b>4. Retention</b>\n"
        "Data is kept while you are registered. It is deleted immediately on /deleteme request or within 30 days of last activity.\n\n"
        "<b>5. Your rights</b>\n"
        "Access, rectification, <b>erasure</b> (/deleteme), restriction, portability and withdrawal of consent.\n"
        "Requests: gdpr@amiga-migrant.cz\n\n"
        "<b>6. Third-party processors</b>\n"
        "• Google LLC — Calendar & Sheets (data processing agreement via Google Workspace)\n"
        "• Telegram Messenger — message transport only\n"
        "• Render Inc. — hosting\n"
        "No data is sold or shared for commercial purposes.\n\n"
        "<b>7. GDPR contact</b>\n"
        "gdpr@amiga-migrant.cz\n\n"
        "<b>8. Supervisory authority</b>\n"
        "Úřad pro ochranu osobních údajů (ÚOOÚ)\n"
        "www.uoou.cz"
    ),
}
